src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether the client is active or archived.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>https://help.getharvest.com/api-v2/projects-api/projects/projects/</description>
    <fields>
        <fullName>Bill_By__c</fullName>
        <description>The method by which the project is invoiced.</description>
        <label>Bill By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Tasks</fullName>
                </value>
                <value>
                    <fullName>People</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <description>Client (Account) for the Project</description>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether the project is active or archived.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the project is billable or not.</description>
        <label>Is Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Project notes.</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_Hourly_Rate__c</fullName>
        <description>Rate for projects billed by Project Hourly Rate.</description>
        <label>Project Hourly Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Task__c.object
<CustomObject>
    <description>https://help.getharvest.com/api-v2/tasks-api/tasks/tasks/
Creating this object so a Project Task can be created once and reused across multiple Projects.
Naming this Project Task instead of just Task since SF already has a Task object - can cause confusing when configuring SF if user sees 2 objects labeled Task.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether this task is active or archived.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Task_Assignment__c.object
<CustomObject>
    <description>https://help.getharvest.com/api-v2/projects-api/projects/task-assignments/
Link table between custom Project object and custom Project Task object</description>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the task assignment is billable or not. For example: if set to true, all time tracked on this project for the associated task will be marked as billable.</description>
        <label>Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <description>Rate used when the project’s bill_by is Tasks.</description>
        <label>Hourly Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether the task assignment is active or archived.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Task__c</fullName>
        <description>Has lookup filter that requires a Project Task to be Active</description>
        <label>Project Task</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Active Project Tasks can be used for a Project Task Assignment</errorMessage>
            <filterItems>
                <field>Project_Task__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project_Task__c</referenceTo>
        <relationshipLabel>Project Task Assignments</relationshipLabel>
        <relationshipName>Project_Task_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Task Assignments</relationshipLabel>
        <relationshipName>Project_Task_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task Assignment</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_User_Assignment__c.object
<CustomObject>
    <description>https://help.getharvest.com/api-v2/projects-api/projects/user-assignments/
Link table between custom Project object and standard User object</description>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <description>Rate used when the project’s bill_by is People.</description>
        <label>Hourly Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether the user assignment is active or archived.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project User Assignments</relationshipLabel>
        <relationshipName>Project_User_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An object containing the id and name of the associated user.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_User_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project User Assignment</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <description>https://help.getharvest.com/api-v2/timesheets-api/timesheets/time-entries/</description>
    <fields>
        <fullName>Billable_Rate__c</fullName>
        <description>The billable rate for the time entry. This will be set for every Time Entry record and will be set according to the Project - Bill By field. 
If value = Project, use Project__c.Project_Hourly_Rate__c value
if value = Tasks, use Project_Task_Assignment__c.Hourly_Rate__c
if value = People, use Project_User_Assignment__c.Hourly_Rate__c</description>
        <label>Billable Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the time entry is billable. This will be checked for the Time Entry record if Project__c.Bill_By__c = Project or People and Project__c.Is_Billable__c = true OR if Project__c.Bill_By__c = Task and Project_Task_Assignment__c.Is_Billable__c = true</description>
        <label>Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>Project_User_Assignment__r.Project__r.Client__r.Name</formula>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <description>Number of (decimal time) hours tracked in this time entry.</description>
        <label>Hours</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the time entry has been approved via Timesheet Approval.</description>
        <label>Is Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the time entry has been locked.</description>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the time entry is currently running.</description>
        <label>Is Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes attached to the time entry</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_Task_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Task Assignment</label>
        <referenceTo>Project_Task_Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Task__c</fullName>
        <formula>Project_Task_Assignment__r.Project_Task__r.Name</formula>
        <label>Project Task</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_User_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project User Assignment</label>
        <referenceTo>Project_User_Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Project_User_Assignment__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spent_Date__c</fullName>
        <description>Date of the time entry.</description>
        <label>Spent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Timer_Started_At__c</fullName>
        <description>Date and time the timer was started (if tracking by duration).</description>
        <label>Timer Started At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User_Id__c</fullName>
        <formula>CASESAFEID(Project_User_Assignment__r.User__c)</formula>
        <label>User Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>The Time Entry User is pulled from the Owner of the Weekly Timesheet</description>
        <formula>Weekly_Time_Sheet__r.Owner:User.FirstName &amp; &quot; &quot; &amp; Weekly_Time_Sheet__r.Owner:User.LastName</formula>
        <label>User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weekly_Time_Sheet__c</fullName>
        <label>Weekly Time Sheet</label>
        <referenceTo>Weekly_Time_Sheet__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{00}</displayFormat>
        <label>Time Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Weekly_Time_Sheet__c.object
<CustomObject>
    <description>Will group time entries by week (Monday to Sunday) and by Owner (User)</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Weekly Time Sheet</label>
    <nameField>
        <label>Weekly Time Sheet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TimeEntryController.cls
/**
 * Controller Class for the Time Entry lightning component.
 */
global with sharing class TimeEntryController {

	/**
	 * Data Class that's returned to the Time Entry lightning component.
	 */
	global class TimeEntryData {
		@AuraEnabled
		global TimeEntry timeEntry {get;set;}
		@AuraEnabled
		global List<Map<String,String>> activeProjectUserAssignments {get;set;}
		@AuraEnabled
		global List<Map<String,String>> activeProjectTaskAssignments {get;set;}
	}


	/**
	 * Method to that Returns a TimeEntryData object that's used by the Time Entry lightning component.
	 * @param  String recordId
	 * @return TimeEntryData
	 */
	@AuraEnabled
	global static TimeEntryData getTimeEntryData(String recordId) {
		TimeEntryData ted = new TimeEntryData();
		ted.activeProjectUserAssignments = new List<Map<String,String>>();
		ted.activeProjectTaskAssignments = new List<Map<String,String>>();
		try {
			String projectId; // will be set below if the User creates a Time Entry from a Project record
			Utils.log('recordId = ' + recordId);
			if (String.isNotBlank(recordId)) {
				// let's determine the object type - can be Time_Entry__c, Project__c or Weekly_Time_Sheet__c
				Schema.SObjectType sobjectType = Id.valueOf(recordId).getSObjectType();
				Utils.log('sobjectType = ' + sobjectType);

				if (sobjectType == Schema.Time_Entry__c.SObjectType) {
					// user wants to edit an existing Time Entry
					List<Time_Entry__c> timeEntries = TimeEntriesService.getTimeEntriesByIds(new Set<String> {recordId});

					if (timeEntries.size() != 1) {
						throw new TimeEntryException('Unable to find the Time Entry record.');
					}

					// do validations
					if (timeEntries[0].User_Id__c != UserInfo.getUserId()) {
						throw new TimeEntryException('You do not have access to edit the Time Entry for ' + timeEntries[0].User__c);
					}

					// todo: mark time entries as closed once approved
					if (timeEntries[0].Is_Closed__c) {
						throw new TimeEntryException('This Time Entry is Closed.');
					}

					// todo: mark time entries as locked once submitted for approval
					if (timeEntries[0].Is_Locked__c) {
						throw new TimeEntryException('This Time Entry is Locked.');
					}

					ted.timeEntry = new TimeEntry();
					ted.timeEntry.id = timeEntries[0].Id;
					ted.timeEntry.entryDate = timeEntries[0].Spent_Date__c;
					ted.timeEntry.clientAndProjectName = timeEntries[0].Client__c + ' - ' + timeEntries[0].Project__c;
					ted.timeEntry.projectTaskName = timeEntries[0].Project_Task__c;
					ted.timeEntry.projectUserAssignmentId = timeEntries[0].Project_User_Assignment__c;
					ted.timeEntry.projectTaskAssignmentId = timeEntries[0].Project_Task_Assignment__c;
					ted.timeEntry.notes = timeEntries[0].Notes__c;
					ted.timeEntry.hours = timeEntries[0].Hours__c;
					ted.timeEntry.isRunning = timeEntries[0].Is_Running__c;
					ted.timeEntry.timerStartedAt = timeEntries[0].Timer_Started_At__c;
					return ted;
				} else if (sobjectType == Schema.Weekly_Time_Sheet__c.SObjectType) {
					/* clicked the New button from a Weekly_Time_Sheet__c
					not going to pre-pop anything here - the save logic gets the weekly time sheet based on
					the Entry Date and validates that the timesheet can still be edited
					*/
				} else if (sobjectType == Schema.Project__c.SObjectType) {
					// clicked the New button from a Project__c
					projectId = recordId;
				} 
			}

			// the user wants to create a new Time Entry
			ted.timeEntry = new TimeEntry();
			ted.timeEntry.entryDate = Date.today();
			ted.timeEntry.isRunning = false;

			// project user assignment logic
			List<Project_User_Assignment__c> activeProjectUserAssignments = getActiveProjectUserAssignments();
			if (activeProjectUserAssignments.size() == 0) {
				throw new TimeEntryException('You have no Active Projects or Project User Assignments.');
			}

			// need this next map so we can set the ProjectUserAssignmentId on the activeProjectTaskAssignments below
			// this allow us to build the Task list dynmically based on the selected ProjectUserAssignmentId
			Map<Id,Id> projectIdAndProjectUserAssignmentIds = new Map<Id,Id>();
			for (Project_User_Assignment__c pua : activeProjectUserAssignments) {
				// logic to set the default value
				if (String.isNotBlank(projectId) && projectId == pua.Project__c) {
					ted.timeEntry.projectUserAssignmentId = pua.Id;
				}

				Map<String,String> keyVals = new Map<String,String>();
				keyVals.put('label', pua.Project__r.Client__r.Name + ' - ' + pua.Project__r.Name);
				keyVals.put('value', pua.Id);
				ted.activeProjectUserAssignments.add(keyVals);
				projectIdAndProjectUserAssignmentIds.put(pua.Project__c, pua.Id);
			}

			// project task assignment logic
			List<Project_Task_Assignment__c> activeTasksByProjectId = getActiveProjectTaskAssignments(projectIdAndProjectUserAssignmentIds.keySet());

			if (activeTasksByProjectId.size() == 0) {
				throw new TimeEntryException('You have no Active Project Task Assignments.');
			}

			for (Project_Task_Assignment__c pta : activeTasksByProjectId) {
				Map<String,String> keyVals = new Map<String,String>();
				keyVals.put('projectUserAssignment', projectIdAndProjectUserAssignmentIds.get(pta.Project__c));
				keyVals.put('label', pta.Project_Task__r.Name);
				keyVals.put('value', pta.Id);
				ted.activeProjectTaskAssignments.add(keyVals);
			}
		} catch (Exception e) {
			Utils.errorMsgLightning(e);
		}
		return ted;
	}


	/**
	 * Method to upsert a Time_Entry__c record base on data set on the Time Entry lightning component.
	 * The timer start and stop logic is in the method. Had to pass in the TimeEntry object as a JSON
	 * string do to this SF bug - https://success.salesforce.com/issues_view?id=a1p3A000000EAbLQAW
	 * 
	 * @param  String timeEntryString
	 * @return Map<String,String>
	 */
	@AuraEnabled
	global static Map<String,String> upsertTimeEntry(String timeEntryString) {
		Map<String,String> returnMap = new Map<String,String>();
		Utils.log('timeEntryString = ' + timeEntryString);
		Time_Entry__c te = new Time_Entry__c();
		try {
			TimeEntry timeEntryObj = (TimeEntry)JSON.deserializeStrict(timeEntryString, TimeEntry.class);

			if (String.isNotBlank(timeEntryObj.id)) { // update
				returnMap.put('title', 'Updated the Time Entry');
				te.Id = timeEntryObj.id;

				if (timeEntryObj.isRunning && timeEntryObj.timerStartedAt != null) { // stop it and update Hours
					te.Is_Running__c = false;
					te.Timer_Started_At__c = null;
					if (timeEntryObj.hours == null) {
						timeEntryObj.hours = 0;
					}
					Utils.log('current hours val = ' + timeEntryObj.hours);
					Utils.log('current timerStartedAt val = ' + timeEntryObj.timerStartedAt);

					Utils.log('timerStartedAt.getTime() = ' + timeEntryObj.timerStartedAt.getTime());

					Double millisecondsBetween = Datetime.now().getTime() - timeEntryObj.timerStartedAt.getTime();
					Utils.log('millisecondsBetween = ' + millisecondsBetween);

					Double newHours = millisecondsBetween / 1000 / 3600;
					Utils.log('newHours = ' + newHours);

					te.Hours__c = timeEntryObj.hours + newHours;
					Utils.log('updated hours val = ' + te.Hours__c);
					returnMap.put('message', 'The Timer was stopped.');
				} else { // start it
					returnMap.put('message', 'The Timer was started.');

					te.Is_Running__c = true;
					te.Timer_Started_At__c = Datetime.now();
				}
			} else { // only need to set these on insert
				returnMap.put('title', 'Created the Time Entry');
				returnMap.put('message', 'The Timer was started.');

				te.Spent_Date__c = timeEntryObj.entryDate;
				te.Project_User_Assignment__c = timeEntryObj.projectUserAssignmentId;
				te.Project_Task_Assignment__c = timeEntryObj.projectTaskAssignmentId;
				Weekly_Time_Sheet__c wts = WeeklyTimeSheetsService.getWeeklyTimeSheetForCurrentUser(timeEntryObj.entryDate);
				if (wts.Status__c == Constants.STATUS_SUBMITTED || wts.Status__c == Constants.STATUS_APPROVED) {
					throw new TimeEntryException('The Weekly Time Sheet has already been ' + wts.Status__c + '. You can no longer add a Time Entry to it.');
				}
				te.Weekly_Time_Sheet__c = wts.Id;

				Project_User_Assignment__c pua = getProjectUserAssignmentById(timeEntryObj.projectUserAssignmentId);
				// figure out Bill Rate & Billable based on Project settings
				if (pua.Project__r.Bill_By__c == Constants.BILL_BY_PROJECT) {
					te.Billable_Rate__c = pua.Project__r.Project_Hourly_Rate__c; // get from the Project
					te.Billable__c = pua.Project__r.Is_Billable__c;
				} else if (pua.Project__r.Bill_By__c == Constants.BILL_BY_PEOPLE) {
					te.Billable_Rate__c = pua.Hourly_Rate__c; // get from the Project User Assignment
					te.Billable__c = pua.Project__r.Is_Billable__c;
				} else if (pua.Project__r.Bill_By__c == Constants.BILL_BY_TASKS) {
					Project_Task_Assignment__c pta = getProjectTaskAssignmentById(timeEntryObj.projectTaskAssignmentId);
					te.Billable_Rate__c = pta.Hourly_Rate__c;// get from the Project Task Assignment
					te.Billable__c = pta.Billable__c;
				}
				// only choice is to start it when it's new
				te.Is_Running__c = true;
				te.Timer_Started_At__c = Datetime.now();
			}
			// always set the note
			te.Notes__c = timeEntryObj.notes;
			upsert te;

			returnMap.put('id', te.Id);
		} catch (Exception e) {
			Utils.errorMsgLightning(e);
		}
		return returnMap;
	}


	/**
	 * Get all Active Project_User_Assignment__c for Active Projects for the current user
	 * 
	 * @return List<Project_User_Assignment__c>
	 */
	private static List<Project_User_Assignment__c> getActiveProjectUserAssignments() {
		List<Project_User_Assignment__c> pua = [select Id, Project__c, Project__r.Name, Project__r.Client__r.Name
			from Project_User_Assignment__c
			where User__c = :UserInfo.getUserId() and Is_Active__c = true and Project__r.Is_Active__c = true
			order by Project__r.Client__r.Name, Project__r.Name];

		return pua;
	}


	/**
	 * Get all Active Project_Task_Assignment__c for the projectIds passed in.
	 * 
	 * @param  Set<Id> projectIds
	 * @return List<Project_Task_Assignment__c>
	 */
	private static List<Project_Task_Assignment__c> getActiveProjectTaskAssignments(Set<Id> projectIds) {
		List<Project_Task_Assignment__c> pta = [select Id, Project__c, Project_Task__c, Project_Task__r.Name
			from Project_Task_Assignment__c
			where Project__c in :projectIds and Is_Active__c = true
			order by Project_Task__r.Name]; // could also filter by Project_Task__r.Is_Active__c if needed

		return pta;
	}


	/**
	 * Get a Project_User_Assignment__c record by Id
	 * 
	 * @param  String projectUserAssignmentId
	 * @return Project_User_Assignment__c
	 */
	@TestVisible
	private static Project_User_Assignment__c getProjectUserAssignmentById(String projectUserAssignmentId) {
		return [select Project__r.Bill_By__c, Project__r.Is_Billable__c,
			Project__r.Project_Hourly_Rate__c, Hourly_Rate__c
			from Project_User_Assignment__c
			where Id = :projectUserAssignmentId];
	}


	/**
	 * Get a Project_Task_Assignment__c record by Id
	 * 
	 * @param  String projectTaskAssignmentId
	 * @return Project_Task_Assignment__c
	 */
	@TestVisible
	private static Project_Task_Assignment__c getProjectTaskAssignmentById(String projectTaskAssignmentId) {
		return [select Billable__c, Hourly_Rate__c
			from Project_Task_Assignment__c
			where Id = :projectTaskAssignmentId];
	}
}