src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether the client is active or archived.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Use this Record Type once the Account becomes a Client</description>
        <label>Client</label>
    </recordTypes>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>https://help.getharvest.com/api-v2/projects-api/projects/projects/</description>
    <fields>
        <fullName>Bill_By__c</fullName>
        <description>The method by which the project is invoiced.</description>
        <label>Bill By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Tasks</fullName>
                </value>
                <value>
                    <fullName>People</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Budget_By__c</fullName>
        <description>The method by which the project is budgeted.</description>
        <label>Budget By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>project</fullName>
                    <label>Hours Per Project</label>
                </value>
                <value>
                    <fullName>project_cost</fullName>
                    <label>Total Project Fees</label>
                </value>
                <value>
                    <fullName>task</fullName>
                    <label>Hours Per Task</label>
                </value>
                <value>
                    <fullName>person</fullName>
                    <label>Hours Per Person</label>
                </value>
                <value>
                    <fullName>none</fullName>
                    <label>No Budget</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <description>Client (Account) for the Project</description>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether the project is active or archived.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Hourly_Rate__c</fullName>
        <description>Rate for projects billed by Project Hourly Rate.</description>
        <label>Project Hourly Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_User_Assignment__c.object
<CustomObject>
    <description>https://help.getharvest.com/api-v2/projects-api/projects/user-assignments/
Link table between custom Project object and standard User object</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether the user assignment is active or archived.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project User Assignments</relationshipLabel>
        <relationshipName>Project_User_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An object containing the id and name of the associated user.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_User_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project User Assignment</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Weekly_Time_Sheet__c.object
<CustomObject>
    <description>Will group time entries by week (Monday to Sunday) and by Owner (User)</description>
    <label>Weekly Time Sheet</label>
    <nameField>
        <label>Weekly Time Sheet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchGenerateWeeklyTimesheetTest.cls
/**
 * Tests for BatchGenerateWeeklyTimesheet Class.
 */
@IsTest
private class BatchGenerateWeeklyTimesheetTest {

	/**
	 * Creates a test User with a Sys Admin Profile that can be used for testing.
	 * The User record will be inserted into the Database if the doInsert parameter = true;
	 * 
	 * @param  Boolean doInsert
	 * @return User
	 */
	public static User createTestAdminUser(Boolean doInsert) {
		User u = new User();
		u.FirstName = 'First' + Utils.generateRandomKey();
		u.LastName = 'Last' + Utils.generateRandomKey();
		u.Email = 'email' + Utils.generateRandomKey() + '@somewhere.co';
		u.UserName = u.Email;
		u.ProfileId = [select Id from Profile where Name = :Constants.PROFILE_NAME_SYSTEM_ADMINISTRATOR].Id;
		u.Alias = 'test';
		u.CommunityNickName = u.LastName;
		u.TimeZoneSidKey = 'America/Denver';
		u.LocaleSidKey = 'en_US';
		u.LanguageLocaleKey = 'en_US';
		u.EmailEncodingKey = 'UTF-8';
		u.IsActive = true;
		if (doInsert) {
			insert u;
		}
		return u;
	}


	@IsTest
	static void test_BatchGenerateWeeklyTimesheet() {
		// create 2 active users
		List<User> activeUsers = new List<User> {
			createTestAdminUser(false),
			createTestAdminUser(false)
		};
		insert activeUsers;		

		// create a Client Account
		Account client = new Account();
		client.Name = 'Test Client for Weekly Timesheet';
		client.RecordTypeId = Constants.REC_TYPE_ID_ACCOUNT_CLIENT;
		client.Is_Active__c = true;
		insert client;

		// start off with an inactive Project
		Project__c project = new Project__c();
		project.Name = 'Test Project for Weekly Timesheet';
		project.Is_Active__c = true;
		project.Client__c = client.Id;
		project.Bill_By__c = 'Project';
		project.Budget_By__c = 'project';
		project.Project_Hourly_Rate__c = 100.50;
		insert project;

		Project_User_Assignment__c pua1 = new Project_User_Assignment__c();
		pua1.Project__c = project.Id;
		pua1.User__c = activeUsers[0].Id;
		pua1.Is_Active__c = true;

		Project_User_Assignment__c pua2 = new Project_User_Assignment__c();
		pua2.Project__c = project.Id;
		pua2.User__c = activeUsers[1].Id;
		pua2.Is_Active__c = true;

		insert new List<Project_User_Assignment__c> {pua1, pua2};

		Test.startTest();

		BatchGenerateWeeklyTimesheet bgwt = new BatchGenerateWeeklyTimesheet(Date.today());
		Database.executeBatch(bgwt);

		Test.StopTest();

		List<Weekly_Time_Sheet__c> timesheets = [select Id from Weekly_Time_Sheet__c];
		Utils.log('timesheets.size() = ' + timesheets.size());
		System.assert(timesheets.size() == 2);
	}
}