src/objects/Project__c.object
<CustomObject>
    <description>https://help.getharvest.com/api-v2/projects-api/projects/projects/</description>
    <fields>
        <fullName>Client__c</fullName>
        <description>Client (Account) for the Project</description>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Project notes.</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Task__c.object
<CustomObject>
    <description>https://help.getharvest.com/api-v2/tasks-api/tasks/tasks/
Creating this object so a Project Task can be created once and reused across multiple Projects.
Naming this Project Task instead of just Task since SF already has a Task object - can cause confusing when configuring SF if user sees 2 objects labeled Task.</description>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <description>https://help.getharvest.com/api-v2/timesheets-api/timesheets/time-entries/</description>
    <fields>
        <fullName>Billable_Amount__c</fullName>
        <formula>IF(Billable__c, Billable_Rate__c * Hours__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If Time Entry is Billable, multiplies Billable Rate by Hours</inlineHelpText>
        <label>Billable Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>Project_User_Assignment__r.Project__r.Client__r.Name</formula>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <description>Number of (decimal time) hours tracked in this time entry.</description>
        <label>Hours</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the time entry has been approved via Timesheet Approval.</description>
        <label>Is Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the time entry has been locked.</description>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the time entry is currently running.</description>
        <label>Is Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Locked_Reason__c</fullName>
        <description>Why the time entry has been locked.</description>
        <label>Locked Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes attached to the time entry</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <formula>CASESAFEID(Project_User_Assignment__r.Project__c)</formula>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Task__c</fullName>
        <formula>Project_Task_Assignment__r.Project_Task__r.Name</formula>
        <label>Project Task</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Project_User_Assignment__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spent_Date__c</fullName>
        <description>Date of the time entry.</description>
        <label>Spent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Timer_Started_At__c</fullName>
        <description>Date and time the timer was started (if tracking by duration).</description>
        <label>Timer Started At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Weekly_Time_Sheet__c</fullName>
        <label>Weekly Time Sheet</label>
        <referenceTo>Weekly_Time_Sheet__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{00}</displayFormat>
        <label>Time Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Weekly_Time_Sheet__c.object
<CustomObject>
    <description>Will group time entries by week (Monday to Sunday) and by Owner (User)</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Billable_Amount__c</fullName>
        <label>Total Billable Amount</label>
        <summarizedField>Time_Entry__c.Billable_Amount__c</summarizedField>
        <summaryForeignKey>Time_Entry__c.Weekly_Time_Sheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Hours_for_Week__c</fullName>
        <description>sum up the total hours for the week</description>
        <label>Total Hours for Week</label>
        <summarizedField>Time_Entry__c.Hours__c</summarizedField>
        <summaryForeignKey>Time_Entry__c.Weekly_Time_Sheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Weekly Time Sheet</label>
    <nameField>
        <label>Weekly Time Sheet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TimeEntryListController.cls
/**
 * Controller Class for the Time Entry List lightning component.
 */
global with sharing class TimeEntryListController {

	/**
	 * Data Class that's returned to the Time Entry lightning component.
	 */
	global class TimeEntryListData {
		@AuraEnabled
		global List<TimeEntry> timeEntries {get;set;}
		@AuraEnabled
		global String userName {get;set;}
		@AuraEnabled
		global Decimal totalBillableAmount {get;set;}
		@AuraEnabled
		global Decimal totalHoursForWeek {get;set;}
		@AuraEnabled
		global Boolean canAddTimeEntry {get;set;}
		@AuraEnabled
		global Boolean canSubmitTimeSheet {get;set;}
		@AuraEnabled
		global Boolean canApproveTimeSheet {get;set;}
		@AuraEnabled
		global String sobjectType {get;set;}
	}


	@AuraEnabled
	global static TimeEntryListData getTimeEntryData(String recordId) {
		TimeEntryListData teld = new TimeEntryListData();
		teld.canSubmitTimeSheet = false;
		teld.canApproveTimeSheet = false;
		teld.canAddTimeEntry = false;
		teld.userName = UserInfo.getName();

		teld.timeEntries = new List<TimeEntry>();
		try {
			Weekly_Time_Sheet__c wts;
			Schema.SObjectType sobjectType = Id.valueOf(recordId).getSObjectType();
			Utils.log('sobjectType = ' + sobjectType);

			if (sobjectType == Schema.Weekly_Time_Sheet__c.SObjectType) {
				teld.sobjectType = 'Weekly_Time_Sheet__c';
				List<Weekly_Time_Sheet__c> timesheets = WeeklyTimeSheetsService.getWeeklyTimesheetsByIds(new Set<String> {recordId});
				if (timesheets.size() != 1) {
					throw new TimeEntryException('Unable to find the Weekly Time Sheet for Id = ' + recordId);
				}
				wts = timesheets[0];
				teld.totalBillableAmount = wts.Total_Billable_Amount__c;
				teld.totalHoursForWeek = wts.Total_Hours_for_Week__c;

				if (wts.OwnerId == UserInfo.getUserId() &&
					(String.isBlank(wts.Status__c) || wts.Status__c == Constants.STATUS_IN_PROGRESS)) {
					teld.canSubmitTimeSheet = true;
					teld.canAddTimeEntry = true;
				}

				// show approve button if the timesheet is submitted and if the current user can approve timesheets
				if (wts.Status__c == Constants.STATUS_SUBMITTED && Utils.canUserApproveTimesheets(UserInfo.getUserId())) {
					teld.canApproveTimeSheet = true;
				}

			} else if (sobjectType == Schema.Project__c.SObjectType) {
				teld.sobjectType = 'Project__c';

				wts = WeeklyTimeSheetsService.getWeeklyTimeSheetForCurrentUser(Date.today());

				// can only add entries from the Project - can't submit or approve
				if (String.isBlank(wts.Status__c) || wts.Status__c == Constants.STATUS_IN_PROGRESS) {
					teld.canAddTimeEntry = true;
				}
			}

			// get the time entries for the weekly time sheet id
			List<Time_Entry__c> timeEntries = TimeEntriesService.getTimeEntriesForWeeklyTimeSheetId(wts.Id);

			for (Time_Entry__c te : timeEntries) {
				TimeEntry teObj = new TimeEntry();
				teObj.id = te.Id;
				teObj.clientAndProjectName = te.Client__c + ' - ' + te.Project__c;
				teObj.projectId = te.Project_Id__c;
				teObj.projectTaskName = te.Project_Task__c;
				teObj.entryDate = te.Spent_Date__c;
				teObj.notes = te.Notes__c;
				teObj.hours = te.Hours__c;
				teObj.billableAmount = te.Billable_Amount__c;
				teObj.isRunning = te.Is_Running__c;
				teObj.isLocked = te.Is_Locked__c;
				teObj.isClosed = te.Is_Closed__c;
				teObj.timerStartedAt = te.Timer_Started_At__c;
				teld.timeEntries.add(teObj);
			}
		} catch (Exception e) {
			Utils.errorMsgLightning(e);
		}
		return teld;
	}


	@AuraEnabled
	global static TimeEntryListData toggleTimerForTimeEntry(String recordId, String timeEntryId) {
		try {
			List<Time_Entry__c> timeEntries = TimeEntriesService.getTimeEntriesByIds(new Set<String> {timeEntryId});
			if (timeEntries.size() == 0) {
				throw new TimeEntryException('Unable to find the Time Entry - maybe it was deleted.');
			}
			Time_Entry__c te = timeEntries[0];

			// todo: refactor this code - dupe of code in TimeEntryController
			if (te.Is_Running__c && te.Timer_Started_At__c != null) { // stop timer and update Hours

				if (te.Hours__c == null) {
					te.Hours__c = 0;
				}
				Utils.log('current hours val = ' + te.Hours__c);
				Utils.log('current timerStartedAt val = ' + te.Timer_Started_At__c);
				Utils.log('timerStartedAt.getTime() = ' + te.Timer_Started_At__c.getTime());

				Double millisecondsBetween = Datetime.now().getTime() - te.Timer_Started_At__c.getTime();
				Utils.log('millisecondsBetween = ' + millisecondsBetween);

				Double newHours = millisecondsBetween / 1000 / 3600;
				Utils.log('newHours = ' + newHours);

				te.Hours__c = te.Hours__c + newHours;
				te.Is_Running__c = false;
				te.Timer_Started_At__c = null;
			} else { // start timer
				te.Is_Running__c = true;
				te.Timer_Started_At__c = Datetime.now();
			}
			upsert te;
		} catch (Exception e) {
			Utils.errorMsgLightning(e);
		}
		return getTimeEntryData(recordId);
	}


	@AuraEnabled
	global static TimeEntryListData submitWeeklyTimesheet(String recordId) {
		// making this transactional so it will rollback if anything fails
		Savepoint sp = Database.setSavepoint();
		try {
			List<Weekly_Time_Sheet__c> timesheets = WeeklyTimeSheetsService.getWeeklyTimesheetsByIds(new Set<String> {recordId});
			if (timesheets.size() != 1) {
				throw new TimeEntryException('Unable to find the Weekly Time Sheet for Id = ' + recordId);
			}

			List<Time_Entry__c> timeEntries = TimeEntriesService.getTimeEntriesForWeeklyTimeSheetId(recordId);

			// validate and lock time entries
			if (timeEntries.size() > 0) {
				for (Time_Entry__c te : timeEntries) {
					if (te.Is_Running__c) {
						throw new TimeEntryException('There is a Timer running on a Time Entry. You must stop all Timers before you can submit the Weekly Timesheet.');
					}
					te.Is_Locked__c = true;
					te.Locked_Reason__c = 'Pending Manager Approval';
				}
				update timeEntries;
			}

			// all good - update the status
			Weekly_Time_Sheet__c wts = timesheets[0];
			wts.Status__c = Constants.STATUS_SUBMITTED;
			update wts;
		} catch (Exception e) {
			Database.rollback(sp);
			Utils.errorMsgLightning(e);
		}
		return getTimeEntryData(recordId);
	}


	@AuraEnabled
	global static TimeEntryListData approveWeeklyTimesheet(String recordId) {
		// making this transactional so it will rollback if anything fails
		Savepoint sp = Database.setSavepoint();
		try {
			List<Weekly_Time_Sheet__c> timesheets = WeeklyTimeSheetsService.getWeeklyTimesheetsByIds(new Set<String> {recordId});
			if (timesheets.size() != 1) {
				throw new TimeEntryException('Unable to find the Weekly Time Sheet for Id = ' + recordId);
			}

			List<Time_Entry__c> timeEntries = TimeEntriesService.getTimeEntriesForWeeklyTimeSheetId(recordId);

			// validate and lock time entries
			if (timeEntries.size() > 0) {
				for (Time_Entry__c te : timeEntries) {
					te.Is_Locked__c = true;
					te.Is_Closed__c = true;
					te.Locked_Reason__c = 'Manager Approval';
				}
				update timeEntries;
			}

			// all good - update the status
			Weekly_Time_Sheet__c wts = timesheets[0];
			wts.Status__c = Constants.STATUS_APPROVED;
			update wts;
		} catch (Exception e) {
			Database.rollback(sp);
			Utils.errorMsgLightning(e);
		}
		return getTimeEntryData(recordId);
	}
}