src/objects/Project__c.object
<CustomObject>
    <description>https://help.getharvest.com/api-v2/projects-api/projects/projects/</description>
    <fields>
        <fullName>Client__c</fullName>
        <description>Client (Account) for the Project</description>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Project notes.</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Task__c.object
<CustomObject>
    <description>https://help.getharvest.com/api-v2/tasks-api/tasks/tasks/
Creating this object so a Project Task can be created once and reused across multiple Projects.
Naming this Project Task instead of just Task since SF already has a Task object - can cause confusing when configuring SF if user sees 2 objects labeled Task.</description>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <description>https://help.getharvest.com/api-v2/timesheets-api/timesheets/time-entries/</description>
    <fields>
        <fullName>Billable_Amount__c</fullName>
        <formula>IF(Billable__c, Billable_Rate__c * Hours__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If Time Entry is Billable, multiplies Billable Rate by Hours</inlineHelpText>
        <label>Billable Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>Project_User_Assignment__r.Project__r.Client__r.Name</formula>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <description>Number of (decimal time) hours tracked in this time entry.</description>
        <label>Hours</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the time entry has been approved via Timesheet Approval.</description>
        <label>Is Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the time entry has been locked.</description>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the time entry is currently running.</description>
        <label>Is Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Locked_Reason__c</fullName>
        <description>Why the time entry has been locked.</description>
        <label>Locked Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes attached to the time entry</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <formula>CASESAFEID(Project_User_Assignment__r.Project__c)</formula>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Task__c</fullName>
        <formula>Project_Task_Assignment__r.Project_Task__r.Name</formula>
        <label>Project Task</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Project_User_Assignment__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spent_Date__c</fullName>
        <description>Date of the time entry.</description>
        <label>Spent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Timer_Started_At__c</fullName>
        <description>Date and time the timer was started (if tracking by duration).</description>
        <label>Timer Started At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User_Id__c</fullName>
        <formula>CASESAFEID(Project_User_Assignment__r.User__c)</formula>
        <label>User Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>The Time Entry User is pulled from the Owner of the Weekly Timesheet</description>
        <formula>Weekly_Time_Sheet__r.Owner:User.FirstName &amp; &quot; &quot; &amp; Weekly_Time_Sheet__r.Owner:User.LastName</formula>
        <label>User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weekly_Time_Sheet__c</fullName>
        <label>Weekly Time Sheet</label>
        <referenceTo>Weekly_Time_Sheet__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{00}</displayFormat>
        <label>Time Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Weekly_Time_Sheet__c.object
<CustomObject>
    <description>Will group time entries by week (Monday to Sunday) and by Owner (User)</description>
    <label>Weekly Time Sheet</label>
    <nameField>
        <label>Weekly Time Sheet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TimeEntriesService.cls
/**
 * All common methods for the Time Entry object go here.
 */
public with sharing class TimeEntriesService {

	/**
	 * Get a List of Time Entries for a set of Ids
	 * 
	 * @param  Set<String> ids
	 * @return List<Time_Entry__c>
	 */
	public static List<Time_Entry__c> getTimeEntriesByIds(Set<String> ids) {
		List<Time_Entry__c> timeEntries = [select Id, Hours__c, Client__c, Project__c, Project_Id__c, User__c, User_Id__c,
			Project_Task__c, Is_Closed__c, Is_Locked__c, Is_Running__c, Locked_Reason__c, Spent_Date__c, Notes__c,
			Timer_Started_At__c, Billable_Amount__c
			from Time_Entry__c where Id in :ids order by Spent_Date__c, Client__c, Project__c];
		return timeEntries;
	}


	/**
	 * Get a List of Time Entries for a Weekly Time Sheet Id
	 * 
	 * @param  String id
	 * @return List<Time_Entry__c>
	 */
	public static List<Time_Entry__c> getTimeEntriesForWeeklyTimeSheetId(String id) {
		List<Time_Entry__c> timeEntries = [select Id, Hours__c, Client__c, Project__c, Project_Id__c, User__c, User_Id__c,
			Project_Task__c, Is_Closed__c, Is_Locked__c, Is_Running__c, Locked_Reason__c, Spent_Date__c, Notes__c,
			Timer_Started_At__c, Billable_Amount__c
			from Time_Entry__c where Weekly_Time_Sheet__c = :id order by Spent_Date__c, Client__c, Project__c];
		return timeEntries;
	}
}