src/objects/Weekly_Time_Sheet__c.object
<CustomObject>
    <description>Will group time entries by week (Monday to Sunday) and by Owner (User)</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Billable_Amount__c</fullName>
        <label>Total Billable Amount</label>
        <summarizedField>Time_Entry__c.Billable_Amount__c</summarizedField>
        <summaryForeignKey>Time_Entry__c.Weekly_Time_Sheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Hours_for_Week__c</fullName>
        <description>sum up the total hours for the week</description>
        <label>Total Hours for Week</label>
        <summarizedField>Time_Entry__c.Hours__c</summarizedField>
        <summaryForeignKey>Time_Entry__c.Weekly_Time_Sheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Week_Ending__c</fullName>
        <label>Week Ending</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Week_Starting__c</fullName>
        <label>Week Starting</label>
        <type>Date</type>
    </fields>
    <label>Weekly Time Sheet</label>
    <nameField>
        <label>Weekly Time Sheet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WeeklyTimeSheetsService.cls
/**
 * All common methods for the Weekly Time Sheet object go here.
 */
public with sharing class WeeklyTimeSheetsService {

	/**
	 * Get a List of Weekly Timesheets for a set of Ids
	 * 
	 * @param  Set<String> ids
	 * @return List<Weekly_Time_Sheet__c>
	 */
	public static List<Weekly_Time_Sheet__c> getWeeklyTimesheetsByIds(Set<String> ids) {
		List<Weekly_Time_Sheet__c> weeklyTimesheets = [select Id, Name, Status__c, Week_Starting__c, Week_Ending__c,
			Total_Billable_Amount__c, Total_Hours_for_Week__c, OwnerId
			from Weekly_Time_Sheet__c
			where Id in :ids];
		return weeklyTimesheets;
	}


	/**
	 * Get the Weekly Timesheet Id based on the current user and the Date parameter
	 * 
	 * @param  Date dt
	 * @return Weekly_Time_Sheet__c
	 */
	public static Weekly_Time_Sheet__c getWeeklyTimeSheetForCurrentUser(Date dt) {
		List<Weekly_Time_Sheet__c> weeklyTimesheets = [select Id, Name, Status__c, Week_Starting__c, Week_Ending__c,
			Total_Billable_Amount__c, Total_Hours_for_Week__c, OwnerId
			from Weekly_Time_Sheet__c
			where OwnerId = :UserInfo.getUserId() and Week_Starting__c <= :dt and Week_Ending__c >= :dt];

		// do validations
		if (weeklyTimesheets.size() == 0) {
			throw new TimeEntryException('Unable to find a Weekly Time Sheet for Date = ' + dt);
		} else if (weeklyTimesheets.size() > 1) {
			throw new TimeEntryException('More than one Weekly Time Sheet found for Date = ' + dt);
		}
		return weeklyTimesheets[0];
	}
}